# Generated by Django 2.1.7 on 2019-02-23 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_articlestatistic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlestatistic',
            name='article',
        ),
        migrations.DeleteModel(
            name='ArticleStatistic',
        ),
    ]
