# Generated by Django 2.1.7 on 2019-02-23 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20190223_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='comment_article',
        ),
    ]
