# Generated by Django 2.1.7 on 2019-03-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_auto_20190223_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='mainornot',
            field=models.CharField(default='Hayır', max_length=50),
        ),
    ]
